### ISSUE TITLE
Dubbio file di configurazione

### ISSUE THREAD

**Issue by Mas7ro** [vincenzogianfelice/RaspberryAP#1]
Ciao Vincenzo,
premetto che non sono pratico di github, e non so se ho fatto bene a contattarti qui, ma non sono sicuro di come configurare il parametro ESSID_CHECK. Nel mio raspberry tutti gli AP registrati si trovano in /etc/wpa_supplicant/wpa_supplicant.conf. quindi come lo configuro correttamente?
Grazie
Andrea

**Comment by gianfelicevincenzo** [comment]
Ciao @Mas7ro. In `ESSID_CHECK` vanno tutti gli AP dove verranno usati dal RPI per collegarsi. Tra tutti quelli che elenchi, si collegherà a quello disponibile "nei paragi". Quindi per ogni "Nome del WIFI" deve esserci associato, a sua volta, un file di configurazione relativo alla connessione (il file con la WPA, per farla breve) altrimenti il tuo RPI non conoscere la WPA per collegarsi. Quindi avrai:

`ESSID_CHECK=WIFI_1:/percorso/file/di/configurazione/WIFI_1.conf,WIFI_2:/percorso/file/di/configurazione/WIFI_2.conf, ....`

Quindi se hai tutto nel file **wpa_supplicant.conf**, non va bene.
Devi spostare ogni configurazione in un file separato e indicare il percorso di quest'ultimo al campo dell'opzione `ESSID_CHECK`  (tra l altro e' buona norma creare file separati per ogni configurazione AP, invece di ammucchiare tutto in un solo file).
